# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37dddee0ee5fd1b5f872db4caa73fa233f95365becffae5f22c47280ec39aea909857aeaac4ec532633dcaca24621054f27440958c7b66991cfdf712c68dda81

test:
  secret_key_base: 4ff2df1c5728c1b8ce05f1bfe6e1422885edffb4219a6119fc3d76498c458475a6e4af8fdfe01657fe5bb951361a000b5d9c008af86f433feae95822a0f41a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
